language: python
python:
- 2.7
env:
  matrix:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1
  global:
    secure: ! 'SgJJ5vQeGAyhMqIQoDQW9F9n+c345/scxCCD94bkyDk5d3zro5/imUWUQvXf

      zatSjhC3N64icL4kg1YXdjk+fHHSOfTj7cSGK+F9T7+qjcCFy74RnC4pv+OU

      B4BiKQvgu6fOhVX1dbfuB7Ge1C8hML9aW79YQ0vINHKKeTORzuM='
install:
- pip install -q Django==$DJANGO_VERSION --use-mirrors
- pip install . --use-mirrors
- export DEBUG=True
script: make test
notifications:
  email: false
